'use client'


import '../styles/globals.css'
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] })
import { SessionProvider } from 'next-auth/react';
import NextAuthProvider from './NextAuthProvider';
import { Metadata } from 'next'
import { RecoilRoot } from 'recoil';

// export const metadata: Metadata = {
//   title: 'Instagram 2.0',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children, 
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <NextAuthProvider> */}
        <SessionProvider>
          <RecoilRoot>
        {children}
        </RecoilRoot>
        </SessionProvider>
       {/* </NextAuthProvider> */}
        </body>
    </html>
  )
}
